### ISSUE TITLE
コマンドについて

### ISSUE THREAD

**Issue by friend1ws** [ncc-ccat-gap/ncc-ccat-gap-pages#7]
`$ head -n 12 example/simulate_read1.fq`
や
`$ samtools view example/simulate.sam | head -n 4`
などは、それ自体がFASTQやSAMのフォーマットの上に記載されているものだと勘違いを与えかねないので（多分勘違いされる気がする）、削除してしまった方が良い気がする。

**Comment by aokad** [comment]
削除しました
